frase = 'Curso em Vídeo Python'
frase2 = '   Curso em Vídeo Python   '
frase3 = 'Curso em Vídeo Python'
frase4 = frase3.replace('Python', 'Android')
frase5 = 'Curso em Vídeo de Python'
dividido = frase.split()
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[:14])
print(frase[0:])
print(frase[1:15])
print(frase[1:15:2])
print(frase[1::15])
print(frase[::2])
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(len(frase))
print(len(frase2))
print(len(frase2.strip()))
print(len(frase3.replace('Python', 'Android')))
print(frase3)
print(frase4)
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.find('Vídeo'))
print(frase.find('video'))
print(frase.lower().find('vídeo'))
print(frase.upper().find('VÍDEO'))
print(frase5.split())
print(dividido[0])
print(dividido[2][3])