print('----------Desafio 03----------')
numero1 = input('Digite um número! ')
numero2 = input('Digite outro número! ')
soma = int(numero1) + int(numero2)
print('A soma dos números digitados é: ' + str(soma))
