print('----------Desafio 02----------')
diaNascimento = input('Qual é o dia em que você nasceu? ')
mesNascimento = input('Qual é o mês em que você nasceu? ')
anoNascimento = input('Qual é o ano em que você nasceu? ')
print('Você nasceu no dia ' + diaNascimento + ' de ' + mesNascimento + ' de ' + anoNascimento)
